### ISSUE TITLE
Plans to support other providers

### ISSUE THREAD

**Issue by Sh4d1** [dvassallo/s3-benchmark#1]
Hey,

Are you considering implementing other s3 providers?

**Comment by dvassallo** [comment]
No plans to do that at the moment, but it would be interesting to see. What I will likely do next is measure S3 performance from Lambda.

**Comment by copumpkin** [comment]
@dvassallo would also be interesting to see how Fargate and CodeBuild fare, if you're branching out to less serverful workloads :)

**Comment by briangold** [comment]
I'm not sure what @Sh4d1 meant by "providers", but I opened #3 to extend support for custom endpoints. That's all I needed to use this benchmark against an S3-compatible storage provider (Pure Storage FlashBlade, in my case). It should work with Minio or others, although I haven't tried it.

**Comment by Sh4d1** [comment]
@briangold that was what I meant ;)

**Comment by wanghq** [comment]
While there are many S3 compatible storage providers, there are not many EC2 compatible VM instance providers, so it requires some effort to support other providers to measure the storage+compute performance within the same provider/region.

**Comment by dvassallo** [comment]
PR #3 from @briangold has been merged. This allows testing against other S3-compatible endpoints, and I believe it can also be used to test against S3’s VPC endpoint (without passing through the internet).

@wanghq true, but the tool doesn’t use the EC2 API. It can run from Linux/Windows/Mac host. So I expect it to work outside of AWS.

**Comment by zaquestion** [comment]
@dvassallo or anyone really, I'm trying to get any sense for the difference between s3 list latency between the public and vpc endpoints. Unfortunately I'm not well positioned to actually test this myself. If anybodies run the tool against a vpc endpoint and compared I'd love to know the avg latency.
