### ISSUE TITLE
Handling AWS profiles

### ISSUE THREAD

**Issue by wolruf** [dvassallo/s3-benchmark#5]
Hello, it would be nice to have a --profile option to indicate which credentials to use in .aws/credentials

**Comment by dvassallo** [comment]
Hi! You can already do this by setting an env variable. For example, to use the "test" profile, you can run the benchmark like this:

    export AWS_PROFILE=test && ./s3-benchmark

**Comment by wolruf** [comment]
Thanks, I was trying to run it from home and I understand it's only supposed to be run within EC2.
